let homes = [
    {
        "id": 1,
        "name": "Natalie's Suit",
        "type": "apartment",
        "price": 50,
        "capacity": 4,
        "image": "View/pictures/home-1.jpg",
        "location": "Sofia",
        "booked": 10,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true, 
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 2,
        "name": "Apartment Sofia View",
        "type": "apartment",
        "price": 30,
        "capacity": 2,
        "image": "View/pictures/home-2.jpg",
        "location": "Sofia",
        "booked": 56,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 3,
        "name": "Sea View Apartment",
        "type": "apartment",
        "price": 35,
        "capacity": 3,
        "image": "View/pictures/home-3.jpg",
        "location": "Varna",
        "booked": 80,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 4,
        "name": "City's Apartment",
        "type": "apartment",
        "price": 40,
        "capacity": 4,
        "image": "View/pictures/home-4.jpg",
        "location": "Varna",
        "booked": 34,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 5,
        "name": "Sky Home",
        "type": "apartment",
        "price": 67,
        "capacity": 4,
        "image": "View/pictures/home-5.jpg",
        "location": "Sofia",
        "booked": 97,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 6,
        "name": "Dreams Apartment",
        "type": "apartment",
        "price": 23,
        "capacity": 1,
        "image": "View/pictures/home-6.jpg",
        "location": "Sofia",
        "booked": 34,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 7,
        "name": "Roger's Design Apartment",
        "type": "apartment",
        "price": 90,
        "capacity": 3,
        "image": "View/pictures/home-7.jpg",
        "location": "Sofia",
        "booked": 95,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 8,
        "name": "Sunshine Apartment",
        "type": "apartment",
        "price": 90,
        "capacity": 3,
        "image": "View/pictures/home-8.jpg",
        "location": "Sofia",
        "booked": 123,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 9,
        "name": "Angela's suit",
        "type": "apartment",
        "price": 55,
        "capacity": 3,
        "image": "View/pictures/home-9.jpg",
        "location": "Sofia",
        "booked": 54,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 10,
        "name": "Nice Place",
        "type": "apartment",
        "price": 20,
        "capacity": 1,
        "image": "View/pictures/home-10.jpg",
        "location": "Sofia",
        "booked": 15,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 11,
        "name": "Elina's Place",
        "type": "apartment",
        "price": 45,
        "capacity": 3,
        "image": "View/pictures/home-11.jpg",
        "location": "Varna",
        "booked": 98,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 12,
        "name": "Smart Home",
        "type": "apartment",
        "price": 34,
        "capacity": 3,
        "image": "View/pictures/home-12.jpg",
        "location": "Varna",
        "booked": 10,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 13,
        "name": "Alexa's dream place",
        "type": "apartment",
        "price": 76,
        "capacity": 2,
        "image": "View/pictures/home-13.jpg",
        "location": "Varna",
        "booked": 34,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 14,
        "name": "Beach Sea View Apartment",
        "type": "apartment",
        "price": 65,
        "capacity": 4,
        "image": "View/pictures/home-14.jpg",
        "location": "Varna",
        "booked": 340,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 15,
        "name": "My Favorite Place",
        "type": "apartment",
        "price": 110,
        "capacity": 2,
        "image": "View/pictures/home-15.jpg",
        "location": "Varna",
        "booked": 23,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 16,
        "name": "Go Home Apartment",
        "type": "apartment",
        "price": 66,
        "capacity": 3,
        "image": "View/pictures/home-16.jpg",
        "location": "Sofia",
        "booked": 231,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 17,
        "name": "Party Zone Apartment",
        "type": "apartment",
        "price": 200,
        "capacity": 10,
        "image": "View/pictures/home-17.jpg",
        "location": "Sofia",
        "booked": 14,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 18,
        "name": "Green Stay",
        "type": "apartment",
        "price": 34,
        "capacity": 2,
        "image": "View/pictures/home-18.jpg",
        "location": "Varna",
        "booked": 879,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 19,
        "name": "Jana's Home",
        "type": "apartment",
        "price": 76,
        "capacity": 3,
        "image": "View/pictures/home-19.jpg",
        "location": "Sofia",
        "booked": 78,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 20,
        "name": "Group Home",
        "type": "apartment",
        "price": 155,
        "capacity": 8,
        "image": "View/pictures/home-20.jpg",
        "location": "Varna",
        "booked": 231,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 21,
        "name": "Vesta Home",
        "type": "apartment",
        "price": 76,
        "capacity": 4,
        "image": "View/pictures/home-21.jpg",
        "location": "Varna",
        "booked": 112,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 22,
        "name": "Neptun Suit",
        "type": "apartment",
        "price": 23,
        "capacity": 2,
        "image": "View/pictures/home-22.jpg",
        "location": "Varna",
        "booked": 531,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 23,
        "name": "Rose Home",
        "type": "apartment",
        "price": 76,
        "capacity": 4,
        "image": "View/pictures/home-23.jpg",
        "location": "Varna",
        "booked": 243,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 24,
        "name": "Fantasia Suit",
        "type": "apartment",
        "price": 34,
        "capacity": 2,
        "image": "View/pictures/home-24.jpg",
        "location": "Varna",
        "booked": 432,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 25,
        "name": "Water Apartment",
        "type": "apartment",
        "price": 98,
        "capacity": 4,
        "image": "View/pictures/home-25.jpg",
        "location": "Varna",
        "booked": 14,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 26,
        "name": "Mark's Favorite Apartment",
        "type": "apartment",
        "price": 23,
        "capacity": 2,
        "image": "View/pictures/home-26.jpg",
        "location": "Varna",
        "booked": 632,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 27,
        "name": "English Home",
        "type": "apartment",
        "price": 45,
        "capacity": 3,
        "image": "View/pictures/home-27.jpg",
        "location": "Varna",
        "booked": 123,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 28,
        "name": "Sea Suit",
        "type": "apartment",
        "price": 90,
        "capacity": 4,
        "image": "View/pictures/home-28.jpg",
        "location": "Varna",
        "booked": 91,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 29,
        "name": "Penthouse Sea View",
        "type": "apartment",
        "price": 200,
        "capacity": 4,
        "image": "View/pictures/home-29.jpg",
        "location": "Varna",
        "booked": 24,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 30,
        "name": "Vendetta Pethhouse",
        "type": "apartment",
        "price": 230,
        "capacity": 5,
        "image": "View/pictures/home-30.jpg",
        "location": "Varna",
        "booked": 543,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 31,
        "name": "Aloha Home",
        "type": "apartment",
        "price": 98,
        "capacity": 4,
        "image": "View/pictures/home-31.jpg",
        "location": "Sofia",
        "booked": 345,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 32,
        "name": "Georgeus Suit",
        "type": "apartment",
        "price": 23,
        "capacity": 3,
        "image": "View/pictures/home-32.jpg",
        "location": "Sofia",
        "booked": 19,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 33,
        "name": "Max's Favorite",
        "type": "apartment",
        "price": 45,
        "capacity": 2,
        "image": "View/pictures/home-33.jpg",
        "location": "Sofia",
        "booked": 111,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 34,
        "name": "Salvatore Suit",
        "type": "apartment",
        "price": 23,
        "capacity": 2,
        "image": "View/pictures/home-34.jpg",
        "location": "Sofia",
        "booked": 421,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 35,
        "name": "Orchard",
        "type": "apartment",
        "price": 76,
        "capacity": 3,
        "image": "View/pictures/home-35.jpg",
        "location": "Sofia",
        "booked": 23,
        "pets": true,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 36,
        "name": "The Cherries",
        "type": "apartment",
        "price": 87,
        "capacity": 3,
        "image": "View/pictures/home-36.jpg",
        "location": "Sofia",
        "booked": 921,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
    {
        "id": 37,
        "name": "The Cuckoo’s Nest",
        "type": "apartment",
        "price": 26,
        "capacity": 2,
        "image": "View/pictures/home-37.jpg",
        "location": "Sofia",
        "booked": 231,
        "pets": false,
        "equipment": {
            "parking": false,
            "swimmingPool": false,
            "smoking": true,
            "bath": true,
            "airConditioning": true,
            "wifi": true,
            "tv": true,
            "coffeeMachine": true,
            "accessibility": false,
            "basicAmenities": true,
        }
    },
];